config/routes.rb
Rails.application.routes.draw do
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy', as: :task_destroy

  resources:tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>All the tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
    <% if task.completed == false %>
      <%= "☐" %>
    <% elsif task.completed == true %>
      <%= "✔" %>
    <% end %>
      <%= link_to task.title, task_path(task.id) %>
      <%= link_to "🗑️", task_path(task), method: :delete %>
      </li>
  <% end %>

</ul>

<p>
  <%= link_to "Add new task", new_task_path  %>
</p>

app/views/tasks/new.html.erb
<!--
<form action="/tasks" method="POST">
  <input type="text" name="title">
  <input type="text" name="details">
  <input type="submit">
</form> -->
<%= render 'form' %>

<p>
  <%= link_to "Back to the list", tasks_path(@tasks)  %>
</p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>
  <% if @task.completed == false %>
      <%= "☐ This task is not yet completed..." %>
    <% elsif @task.completed == true %>
      <%= "✔ You have completed this task!" %>
    <% end %>
</p>

<p>
  <%= link_to "Edit this task", edit_task_path(@task) %>
</p>

<p>
  <%= link_to "Back to the list", tasks_path(@tasks)  %>
</p>